### ISSUE TITLE
Project Maintainance Issues

### ISSUE THREAD

**Issue by crutchcorn** [Xunnamius/unified-utils#96]
While working on a PR/fork for #95 I noticed a few problems with the project's scaffolding that I don't seem to see answers for in any of the docs:

1) I get an integrity failure when doing `npm ci`. I had to regenerate `package-lock.json` to solve this
2) I get a peer resolution failure after regenerating this file, leading to failures of package installation in new versions of NPM. To solve this, I had to change:

```diff
-    "typedoc": "^0.23.24",
+    "typedoc": "^0.24.8",
```

In the root package.json

3) When trying to make a commit, I get errors like so:

```
CONTRIBUTING.md
  1:1  error  Error: Could not find module `lint-fenced-code-flag-case`
Error: Cannot find package 'lint-fenced-code-flag-case' imported from /Users/corbincrutchley/git/Unicorn/unified-utils/
```

I believe this is because we're not linking the internal packages to global scope, leading to a resolution issue. I could fix this by deep-linking the plugins URLs in the Remark plugin

**Comment by Xunnamius** [comment]
Hi, thanks for your interest :)

The first issue happens because I'm using several patched packages served by a CDN. The CDN always offers the latest version of a package, and the patched packages are rebased on the latest releases from upstream, resulting in an integrity failure (a mismatch between the older release package-lock.json expects and the newer release the CDN returns). This can be fixed by appending a version number to the CDN urls, effectively pinning the packages, which I do in my latest projects. Unfortunately, this repo is old enough that I haven't yet updated it.

The second issue is probably because I was using a bleeding edge version of typedoc that typescript didn't yet support... or perhaps it was the other way around.

I'm in the middle of a sort of re-organization of my projects moving them to a uniform local development/CI/CD flow while at the same time exploring the pros and cons of different repository structures, so there are little sharp edges like this right now unfortunately. My goal this year is to abstract away all of this nuisance to a few dev packages, similar to kcd-scripts.

I'll update the npm dependencies and push new `package*.json` files in a moment :)

**Comment by crutchcorn** [comment]
Thanks so much for the rapid and in depth response!

> My goal this year is to abstract away all of this nuisance to a few dev packages, similar to kcd-scripts.

Please let me know when you start working on this in depth! We're facing a similar set of challenges with the @tanstack projects. I'd love to collaborate on how we could consolidate our tooling or at very least learn from one another's efforts

**Comment by Xunnamius** [comment]
Hey @crutchcorn, will do! Also, the repo should be in a good state now (`rm node_modules`, `git pull`, `npm i` should do the trick). I also updated things to work with the latest releases of unified/remark. All unit and integration tests pass except the ones involving `--use`, which seems to be a bug in unified-cli/remark-cli itself.

**Comment by crutchcorn** [comment]
Confirmed that your fixes resolves this issue! Thanks for tackling this!
